### ISSUE TITLE
KeyError in orders Dictionary : 'market'

### ISSUE THREAD

**Issue by bedinsky** [whittlem/coinbaseprotracker#2]
on line 88 orders['market'] causes KeyError exception and script exits after retrieving a BTC-EUR profile

`for market in orders['market'].sort_values().unique():`

I have other 3 profile and script works with them
pycryptobot is able to run such profile but there were not operations in 2 days
I'm new of coinbase pro, is there something wrong with the profile ?

regards

I've added this check to skip exception
`            
try:
   _market = orders['market']
except KeyError as ke:
  print ('*** no market ***')
  continue
`

**Comment by whittlem** [comment]
I fixed this today. Try a "git pull" and see if it works for you.

**Comment by bedinsky** [comment]
thank you very much
