### ISSUE TITLE
Exception: Bot for ETH-EUR got an exception: ValueError('Trade amount is too small (>= 10).')

### ISSUE THREAD

**Issue by bedinsky** [whittlem/coinbaseprotracker#6]
Why did I got such exception ?

I understand that there must be a minimun trade amount
`MINIMUM_TRADE_AMOUNT = 10`

I do not understand why MINIMUM_TRADE_AMOUNT is an absolute value, should it be calculated from a ratio between 
ETH/EUR ?

In my ETH-EUR portfolio there are 0.07188487 ETH, I see there is another check on an absolute value which is 0.001
(even if in exception is written 0.1)

`elif state.last_action == 'BUY' and account.getBalance(app.getBaseCurrency()) < 0.001:
            raise Exception('Insufficient available funds to place sell order: ' + str(account.getBalance(app.getBaseCurrency())) + ' < 0.1 ' + app.getBaseCurrency() + "\nNote: A manual limit order places a hold on available funds.")`

**Comment by whittlem** [comment]
You've raised this issue in the wrong project.

Please can you raise your issue here:
https://github.com/whittlem/pycryptobot/issues

**Comment by bedinsky** [comment]
I make my apologies
