### ISSUE TITLE
Bots Limited to 6 and profitandloss.csv not saving

### ISSUE THREAD

**Issue by Olney1** [whittlem/coinbaseprotracker#7]
The tracker is only running a maximum of 6 bots. It wont run the full 10 current Coinbase allowance. 

Also, the profitandloss.csv is not saving.

No console errors are produced, simply only 6 bot results are returned and the CSV is not saved.

**Comment by whittlem** [comment]
I will look into this, thanks.

**Comment by whittlem** [comment]
Are you sure as there is no limitation in the code? It will read in as many bots you as you want from your config.json
